services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: solvro-bot-core
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
